Account data change
KIT-PSE/collab-space-frontend pull request #29
Opened 2023-07-21 12:15 UTC by davph

resolves https://github.com/KIT-PSE/collab-space-app/issues/5

2023-07-25 15:45 UTC, FlorianRaith commented
@davph die `package-lock.json` müsstest du auch wieder herstellen. Deshalb failed der build https://github.com/KIT-PSE/collab-space-frontend/actions/runs/5645582382/job/15291641684?pr=29

2023-07-30 19:47 UTC, mariusfriess requested changes
Ich persönlich würde hier vllt noch kleine Anpassungen machen.

2023-07-30 19:47 UTC, mariusfriess commented on src/views/AccountView.vue
> +          </button>
Ich würde hier vllt. wenn nur die `disabledInputs` Variable verwenden und den Text hier dann abhängig von der Variable anzeigen, also von der Idee her:

```
{{ disabledInputs[0].value ? 'Ändern': 'Speichern' }}
```

Analog dann natürlich für die anderen Inputs / Buttons.

2023-07-30 19:47 UTC, mariusfriess commented on src/views/AccountView.vue
> +  const settings = [ref('Ändern'), ref('Ändern'), ref('Ändern')];
Dann könnte das hier nämlich einfach wegfallen.

2023-07-30 19:47 UTC, mariusfriess commented on src/views/AccountView.vue
> +      const result = await auth.changeAccountData();
Und den Anfang der Methode dann auch entsprechend anpassen. Z.B. so in die Richtung vllt?

```
disabledInputs[index].value = !disabledInputs[index].value;
if (disabledInputs[index].value) {
   // Änderungen speichern
}
```

2023-07-30 21:28 UTC, mariusfriess approved these changes
Also von meiner Seite aus passt so eigentlich

2023-08-01 13:32 UTC, merged